import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowUpRight, Check, Github, Linkedin, Mail, MapPin, Menu, Phone, X } from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/toaster';
import NotFound from '@/pages/not-found';
import { Route, Switch, useLocation, Router as WouterRouter } from 'wouter';

const queryClient = new QueryClient();
const navItems = [{ id: 'about', label: 'About' }, { id: 'experience', label: 'Experience' }, { id: 'projects', label: 'Projects' }, { id: 'skills', label: 'Skills' }, { id: 'contact', label: 'Contact' }];
const experiences = [
  { period: 'Jan 2026 — Present', company: 'Troniqs Rationale Technologies and Services (P) Ltd', role: 'Quality Assurance · Junior Development', project: 'VitaTraq — Healthcare Application', description: 'Performed unit, API and regression testing, improved coverage, reproduced and verified bugs, and collaborated with developers to improve application quality and reliability.', detail: 'Developed features and backend logic with React, Node.js, TypeScript, GraphQL and REST APIs. Managed database changes, fixed bugs, handled security improvements and supported production issues through debugging.' },
  { period: 'Nov 2025 — Jan 2026', company: 'Devaxcel Tech Private Ltd', role: 'Software Developer', project: 'BrainCheck', description: 'Worked with AWS ECS, EC2, Lambda, Step Functions, EventBridge and CloudWatch across cloud deployment, serverless architecture, event-driven workflows, monitoring and troubleshooting.', detail: 'Also worked with Pulumi for infrastructure management and Jenkins for CI/CD automation, building practical knowledge of scalable cloud applications.' },
  { period: 'May 2025', company: 'ShreeVijay Technology Solutions', role: 'Python Programming Intern', project: 'Software development internship', description: 'Gained practical experience in coding, debugging, automation and application development while strengthening problem-solving skills.' },
  { period: 'May 2024', company: 'Zworks Technology', role: 'Web Development Intern', project: 'Dynamic web applications', description: 'Worked with HTML, CSS, PHP, Bootstrap and Laravel to build responsive and dynamic web applications.' },
];
const projects = [['01', 'Sorting Algorithm Analysis', 'Analyzed the runtime performance of Bubble Sort and Insertion Sort using ASP.NET with randomly generated data.'], ['02', 'Alumni Management System', 'Developed an alumni management application using ASP.NET.'], ['03', 'Orphanage Management System', 'Developed a management system using HTML, CSS, Java and MySQL.']];
const skillGroups = [['Programming', 'Java, Python, TypeScript, JavaScript, PHP, C++'], ['Frontend', 'HTML5, CSS3, Bootstrap, React.js, Next.js, React Native'], ['Backend & APIs', 'Node.js, REST APIs, GraphQL, ASP.NET, Laravel'], ['Data', 'MySQL, MongoDB, Redis'], ['Cloud & DevOps', 'AWS, Lambda, Step Functions, SQS, CloudWatch, Pulumi, Docker'], ['Testing & QA', 'Jest, Playwright, Unit, API, Functional, Regression Testing, Debugging'], ['AI & GenAI', 'LLMs, AI Agents, Prompt Engineering, Knowledge Retrieval, Voice AI, AI-assisted Development'], ['AI Tools', 'ChatGPT, Claude']];

function SectionHeading({ number, children }: { number: string; children: ReactNode }) { return <div className="section-heading"><span>{number}</span><i /><strong>{children}</strong></div>; }

function Portfolio() {
  const [mobileOpen, setMobileOpen] = useState(false); const [active, setActive] = useState('about'); const [form, setForm] = useState({ name: '', email: '', message: '' }); const [sent, setSent] = useState(false);
  useEffect(() => { const scroller = document.querySelector<HTMLElement>('.resume-scroll'); if (!scroller) return; const onScroll = () => { const closest = navItems.map((item) => { const element = document.getElementById(item.id); return { id: item.id, distance: element ? Math.abs(element.getBoundingClientRect().top - 110) : Infinity }; }).sort((a, b) => a.distance - b.distance)[0]; if (closest) setActive(closest.id); }; scroller.addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => scroller.removeEventListener('scroll', onScroll); }, []);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMobileOpen(false); };
  const submitForm = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const subject = encodeURIComponent(`Portfolio hello from ${form.name || 'a new connection'}`); const body = encodeURIComponent(`${form.message}\n\nReply to: ${form.email}`); window.location.href = `mailto:j.deepak22lal@gmail.com?subject=${subject}&body=${body}`; setSent(true); };
  return <div className="portfolio-shell">
    <header className="mobile-header"><button onClick={() => scrollTo('about')} className="logo">DL<span>.</span></button><button onClick={() => setMobileOpen(!mobileOpen)} aria-label={mobileOpen ? 'Close menu' : 'Open menu'}>{mobileOpen ? <X /> : <Menu />}</button>{mobileOpen && <nav>{navItems.map((item) => <button key={item.id} onClick={() => scrollTo(item.id)}>{item.label}</button>)}</nav>}</header>
    <aside className="profile-panel"><div><div className="brand-mark">DEEPAK<span>/</span>LAL J</div><div className="profile-intro"><p className="eyebrow"><span className="status-dot" /> Software developer</p><h1>Deepak<br /><em>Lal J</em></h1><p className="profile-summary">I build practical software, test it with care, and keep learning the tools that make useful ideas real.</p></div><div className="profile-facts"><span>Based in<br /><b>Kanyakumari, India</b></span><span>Open to<br /><b>Software roles</b></span></div></div><div className="profile-bottom"><nav className="desktop-nav">{navItems.map((item, index) => <button key={item.id} onClick={() => scrollTo(item.id)} className={active === item.id ? 'active' : ''}><span>0{index + 1}</span><i />{item.label}</button>)}</nav><div className="profile-contact"><a href="mailto:j.deepak22lal@gmail.com" aria-label="Email"><Mail /></a><a href="tel:7708695429" aria-label="Phone"><Phone /></a><a href="https://www.linkedin.com/in/deepak-lal-821717264" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin /></a><a href="https://github.com/Deepaklal22" target="_blank" rel="noreferrer" aria-label="GitHub"><Github /></a><span>© 2026</span></div></div></aside>
    <main className="resume-scroll">
      <section id="about" className="resume-section about-section"><SectionHeading number="01">Profile</SectionHeading><div className="about-grid"><div><p className="kicker">Software Developer / QA / MCA</p><h2>Building software with <em>curiosity</em> and care.</h2></div><div className="about-copy"><p>Software Developer with hands-on experience in building software applications and exploring modern technologies.</p><p>I enjoy solving problems, learning new tools, and adapting to different work environments. I am always looking to strengthen my technical skills and build practical solutions that make a real difference.</p></div></div><div className="stats"><div><b>7.8</b><span>MCA CGPA</span></div><div><b>7.7</b><span>BSc CGPA</span></div><div><b>02</b><span>Internships</span></div><div><b>∞</b><span>Room to learn</span></div></div></section>
      <section id="experience" className="resume-section tinted"><SectionHeading number="02">Experience</SectionHeading><div className="timeline">{experiences.map((experience) => <article key={experience.company}><div className="timeline-meta"><span>{experience.period}</span><b>{experience.company}</b></div><div className="timeline-body"><h3>{experience.role}</h3><p className="project-label">{experience.project}</p><p>{experience.description}</p>{experience.detail && <p>{experience.detail}</p>}</div></article>)}</div></section>
      <section id="projects" className="resume-section"><SectionHeading number="03">Selected Projects</SectionHeading><div className="project-list">{projects.map(([number, title, description]) => <article key={number}><span className="project-number">{number}</span><div><h3>{title}</h3><p>{description}</p></div><ArrowUpRight /></article>)}</div></section>
      <section id="skills" className="resume-section tinted"><SectionHeading number="04">Technical Skills</SectionHeading><div className="skill-grid">{skillGroups.map(([name, list]) => <div key={name}><span className="skill-name">{name}</span><p>{list}</p></div>)}</div></section>
      <section id="education" className="resume-section"><SectionHeading number="05">Education</SectionHeading><div className="education-list"><div><b>Master of Computer Application</b><span>St. Joseph’s College · Trichy</span><strong>7.8</strong></div><div><b>Bachelor of Computer Science</b><span>St. Joseph’s College · Trichy</span><strong>7.7</strong></div><div><b>Higher Secondary Certificate</b><span>Carmel School · Nagercoil</span><strong>85%</strong></div><div><b>Secondary School Leaving Certificate</b><span>Carmel School · Nagercoil</span><strong>79%</strong></div></div></section>
      <section id="contact" className="resume-section contact-section"><SectionHeading number="06">Contact</SectionHeading><div className="contact-grid"><div><h2>Let’s build something <em>useful.</em></h2><p>Have a role, a project, or a good problem to solve? Send me a note.</p><a className="email-link" href="mailto:j.deepak22lal@gmail.com"><Mail /> j.deepak22lal@gmail.com</a><a className="phone-link" href="tel:7708695429"><Phone /> 7708695429</a><div className="location"><MapPin /> Kurusady, Kanyakumari</div></div><form onSubmit={submitForm}><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="you@company.com" /></label><label>Message<textarea required rows={3} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} placeholder="Tell me about the opportunity" /></label><button type="submit">Open email draft <ArrowUpRight /></button>{sent && <p className="sent"><Check /> Your email app should be opening now.</p>}</form></div></section>
    </main>
  </div>;
}

function Router() { return <RoutedErrorBoundary><Switch><Route path="/" component={Portfolio} /><Route component={NotFound} /></Switch></RoutedErrorBoundary>; }
function RoutedErrorBoundary({ children }: { children: ReactNode }) { const [location] = useLocation(); return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>; }
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;